- name: Debian
  hosts: all
  become: yes
  tasks:
    - name: Aktualisiere die Paketlisten
      apt:
        update_cache: yes

    - name: Führe das Dist-Upgrade durch
      apt:
        upgrade: dist
        autoremove: yes

    - name: Bereinige alte Pakete
      apt:
        autoclean: yes

    - name: Entferne nicht mehr benötigte Pakete
      apt:
        autoremove: yes
