- name: UCS Server Upgrade
  hosts: all
  become: yes
  tasks:
      - name: Prune old Kernels
        ansible.builtin.command:
        cmd: "univention-prune-kernels"
      
    - name: Disable App Updates and Upgrade UCS
      ansible.builtin.command:
        cmd: "univention-upgrade --ignoressh --disable-app-updates --noninteractive --updateto 5.0-10"
      register: disable_upgrade_output

    - name: Show Output of Disable App Updates Upgrade
      ansible.builtin.debug:
        var: disable_upgrade_output.stdout

    - name: Enable App Updates and Upgrade UCS
      ansible.builtin.command:
        cmd: "univention-upgrade --ignoressh --enable-app-updates --noninteractive --updateto 5.0-10"
      register: enable_upgrade_output

    - name: Show Output of Enable App Updates Upgrade
      ansible.builtin.debug:
        var: enable_upgrade_output.stdout
